server:
  port: 8080

spring:
  application:
    name: giggle-image
  redis:
    host: localhost
    port: 6379

comfyui:
  server:
    url: http://localhost:8188

logging:
  level:
    com.giggle.image: INFO
    org.springframework.web: INFO 